### ISSUE TITLE
Java stops highlighting after a certain point

### ISSUE THREAD

**Issue by k-poole** [colorer/Colorer-schemes#69] opened 2018-12-27 01:04 UTC
Confirmed an issue with java.hrc by replacing with vbasic.hrc and the issue went away.

Test on tohtml.com eg:

![image](https://user-images.githubusercontent.com/14868054/50461047-671a8580-09b6-11e9-8a59-477073f42818.png)

**Comment by sharpedavid** [comment] 2018-12-31 18:35
I'm the one who reported this over email. I played around with this example and discovered something: only code surrounded by braces is highlighted. So if you surround the whole example with `{...}`, then syntax highlighting works throughout.

![image](https://user-images.githubusercontent.com/1767127/50565780-41a7b780-0ce7-11e9-8793-f4fdd52bef53.png)

I don't think that it should require the braces. I think a common use-case of this tool (_tohtml_) is syntax highlighting snippets, not complete code blocks.

**Comment by ctapmex** [comment] 2019-01-01 08:31
please attach this example

**Comment by k-poole** [comment] 2019-01-01 13:43
![50565780-41a7b780-0ce7-11e9-8793-f4fdd52bef53](https://user-images.githubusercontent.com/14868054/50573391-0227bb00-0e0e-11e9-853c-0511ecfa9aa3.png)
Here ya go @ctapmex 

Also @sharpedavid this isn't specifically tohtml, this is just part of the library that the code uses :)

**Comment by sharpedavid** [comment] 2019-01-01 16:48
I bet he means text instead of image. I won’t be able to post that example until tomorrow, but here’s a simpler example:

With Java syntax highlighting, `System.out.println(“Hello world!”);` does not highlight, but `{System.out.println(“Hello world!”);}` does.

(Posting on mobile.)

**Comment by k-poole** [comment] 2019-01-02 00:15
Ah yep nice one!

@ctapmex does that help?

Cheers guys.

**Comment by ctapmex** [comment] 2019-01-02 13:57
where do you check ? colorer.exe , far, Eclipse ?
if Eclipse - I do not know how to help you. I do not know how to build a plugin for Eclipse

**Comment by k-poole** [comment] 2019-01-02 13:59
@ctapmex any implementation of java.hrc will have this issue. I have confirmed this by replacing it with another HRC file, and the issue goes away. Something in java.hrc is causing it to stop processing the code without curly brackets.

**Comment by k-poole** [comment] 2019-01-02 13:59
You can test it on https://tohtml.com by selecting 'Java' (instead of autodetect) and pasting some code in.

**Comment by ctapmex** [comment] 2019-01-02 14:07
hrc is just the rules. It needs a rule handler (colorer binary, farcolorer, eclipse colorer, etc) . The handler can fail . What handler is used on this site, I do not know. This is not "our" site.
take FarManager https://farmanager.com/download.php?l=en and check file in far text editor  (F4).

**Comment by k-poole** [comment] 2019-01-02 14:15
@ctapmex Yeah I figured as much. I don't know much about how it all works, but I inherited tohtml.com when Oleg could no longer run it. It uses colorer binary I believe, but regardless of that, I confirmed the problem seemingly in the java.hrc file by replacing its contents with another HRC file and just changing "type name=". 

I just did a quick test with Far and reproduced the issue. As shown:
![farjavafail](https://user-images.githubusercontent.com/14868054/50595539-be02ec00-0edb-11e9-8619-bdd31823628b.PNG)

Note the obvious issue with "user" being highlighted when the entire snippet is within {}, but not when outside.

Cheers
-KP

**Comment by ctapmex** [comment] 2019-01-02 14:21
ok.  can you send this file? or I will have to type it manually for tests ;) 
ctapmex at gmail.com

**Comment by ctapmex** [comment] 2019-01-02 14:35
well, I understood what was the matter. I will try to explain through 'google translate'. Colorer doesn't just color the text by seeing keywords and symbols. Coloring goes according to context. If the file has incorrect language syntax, then the coloring will not be correct.
The test case contains the contents of the function. A function must begin with a name and {.

**Comment by k-poole** [comment] 2019-01-02 14:57
Ah okay.

@sharpedavid thoughts? I am no Java expert sorry, so did not even consider this partial syntax issue.

I did a test with https://www.cs.utexas.edu/~scottm/cs307/javacode/codeSamples/PrimeEx.java and it appears to highlight fine.

@ctapmex While that makes sense, the vbasic.hrc file does not seem to work this way, and still highlights  type descriptors such as String, and quoted text such as "user".

Thanks

**Comment by ctapmex** [comment] 2019-01-02 15:15
as far I remember vbasic, this is the correct syntax for it

**Comment by sharpedavid** [comment] 2019-01-02 17:12
Hi everyone, thanks for spending time on this. This all sounds fine to me. It sounds like the library is working as intended.

Really the only reason I reported this is because it appeared to work for half of the sample, but not for the other half. This made me think there was a defect, but I understand now it's working as intended.

Again, thanks for your support, everyone. I recommend closing this ticket.

**Closed** 2019-01-02 17:47 UTC
