### ISSUE TITLE
Issues with "smarty php templates"

### ISSUE THREAD

**Issue by unxed** [colorer/Colorer-schemes#75] opened 2019-05-22 12:48 UTC
Smarty allows css/js code inside templates and not processes expressions if next character after `{` is space or newline.

But colorer treats `{<newline>` as smarty expression.

`{<space>` is ok, but additional space symbol is needed after `}`, or `}` will be shown as error.

Also `;` inside css are shown as errors.

![Снимок экрана в 2019-05-22 15-44-19](https://user-images.githubusercontent.com/1151423/58175533-006d6f80-7ca9-11e9-9e30-840f0dd5c72f.png)

**Comment by unxed** [comment] 2019-05-23 17:28
@lazyeugene ?

**Comment by lazyeugene** [comment] 2019-05-23 17:43
I think, 'tpl' is not very specific extension to use it exclusively for smarty. Currently tpl files can be highlighted as turbo prolog and as config file if first line starts with ; [ or #
Why don't you use "smarty" extension?
If there is a reason, you can select color scheme from farcolorer menu.

**Comment by lazyeugene** [comment] 2019-05-23 17:49
Anyway, a good start is to provide **text** content to review in addition to a picture.

**Comment by unxed** [comment] 2019-05-23 21:21
@lazyeugene sample of buggy processed js/css as requested:

```
<html>
<head></head>
<body>
<script>
    function sample1() {
    }
    function sample2() { 
    }
    function sample3() { 
    } 
</script>
<style>
    .sample1 {
        color: #fff;
    }
    .sample2 { 
        color: #fff;
    }
    .sample3 { 
        color: #fff;
    } 
    .sample4 { 
        color: #fff;
    } 
</style>
</body>
</html>
```

**Comment by lazyeugene** [comment] 2019-05-24 04:30
Well, the problem is in smarty syntax - it uses the same delimiter as used in javascript/css - curly bracers. So it is pretty difficult to separate the case when it is the js function body start (or css rule start) from the bracers used for smarty tags.
Colorer uses regexps to parse, so it is pretty tricky task.
I never used smarty in my work, so this scheme was written just for fun and I don't understand smarty templates in details. Here is a patched scheme that does a quick fix for this problem. Please, test it.

PS I have no plans to develop colorer schemes, so a little quick fix is the best I can do.
[smarty.hrc.zip](https://github.com/colorer/Colorer-schemes/files/3215103/smarty.hrc.zip)

**Comment by unxed** [comment] 2019-05-24 07:58
This version is much better. There are still some issues (`<script>` and `<style>` tags are highlighted as smarty tags on cursor hit and smarty tags like `{if` are not hightlighted now; okay, the vinaigrette of smarty/html/css/js itself is not a best possible design), but it is a good starting point for me to experiment with scheme development by myself. Thanks!

Btw, what about treating as smarty templates all `.tpl` files with first line starting with `{` or `<` symbols?

**Comment by unxed** [comment] 2019-05-24 09:32
UPD: this scheme has almost all problems solved. Minor problems left:
- curly brackets in embed javascript code are not highlighted on cursor hit
- embed css is highlighted poorly
 
[smarty.zip](https://github.com/colorer/Colorer-schemes/files/3216166/smarty.zip)

**Comment by AnrDaemon** [comment] 2019-05-25 08:35
Smarty uses configurable tag separators. In some projects, I use "$( … )" tags for example.
Speaking of selecting highlights by extension, you can change that by introducing an appropriate `~hrc/auto/` file. F.e. this is what I have for modules used in one of my projects:
```xml
<?xml version="1.0" encoding='UTF-8'?>
<!DOCTYPE hrc PUBLIC
	"-//Cail Lomecb//DTD Colorer HRC take5//EN"
	"http://colorer.sf.net/2003/hrc.dtd"
>
<hrc version="take5" xmlns="http://colorer.sf.net/2003/hrc"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://colorer.sf.net/2003/hrc http://colorer.sf.net/2003/hrc.xsd"
 >

<annotation><documentation>
  Dummy MCSC scheme.
</documentation></annotation>

<prototype name="MCSC.sh" group="scripts" description="MCSC dummy scheme">
  <filename>/\.(mcsc)$/i</filename>
</prototype>

<type name="MCSC.sh">

  <import type="shell"/>

	<scheme name="MCSC.sh">
		<inherit scheme="shell"/>
	</scheme>

</type>
</hrc>
```

**Comment by AnrDaemon** [comment] 2022-01-24 07:11
Speaking about Smarty vs. JS distinction - if curly brace is immediately followed by whitespace (this including line terminator), it is NOT Smarty. But yet again, assuming tag separators to be only braces is not correct. Scheme (aside from all other deficiencies) has a very limited applicability.

**Comment by ctapmex** [comment] 2024-05-04 08:51
I have corrected the operation of the circuit in 1ef8c8cfc2487a91fff300111638dc5f82f94ddc . But there is such an error (in the picture), I do not know yet how to fix it. The problem is only with xml tags.

![image](https://github.com/colorer/Colorer-schemes/assets/1277115/94278fb2-c005-472f-9b91-501184c2bb73)

**Comment by unxed** [comment] 2024-05-04 09:57
It's known problem. Colorer engine does not interpret "if" conditions of Smarty, so it can not distinguish, if both opening and closing b tags present in code, only one of them or none.

**Comment by unxed** [comment] 2024-05-04 10:08
It's known problem. Colorer engine does not interpret "if" conditions of Smarty, so it can not distinguish, if both opening and closing b tags present in code, only one of them or none.

Anyway, it's much much better now, thank you very much!

**Closed** 2024-05-04 10:30 UTC

**Comment by unxed** [comment] 2024-10-10 20:15
У нас тут недоработка обнаружилась небольшая. Вот этот smarty-код всё ещё некорректно раскрашивается.

```
<script>
    $(document).ready(function() { 
        {if $test}
            $('#action-pending').on('click', function(e) {
                // этот код не должен краситься как код smarty, а он красится!
                window.location = '?action=pending&list=' + list;
                return false;
            });
        {/if}
    }); 
</script>

<style>
    .appeal-content {
        background-color: #eee;
        padding: 10px;
    }

    table.tablesorter tr td table tr.monitor td {
        border-bottom: 2px solid white;
        color: white;
        background-color: red;
        cursor: pointer;
    }
</style>

```

**Comment by unxed** [comment] 2024-10-13 08:09
В принципе проблема выше решается заменой { и } на {ldelim} и {rdelim}, хоть это и многословнее и хуже читается. Так что лучше бы починить всё же.

И ещё с такой конструкцией проблемы:
```
        {literal}
            var tileUrl = '//{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
        {/literal}
```

— {z}, {x}, {y} подсвечиваются как код Smarty, хотя и не должны.

**Comment by unxed** [comment] 2024-10-20 12:08
Для истории: тут всё доделано.
