### ISSUE TITLE
backslashes in python

### ISSUE THREAD

**Issue by Guest007** [colorer/Colorer-schemes#100] opened 2020-10-22 13:10 UTC
Not correctly parse backslashes
![2020-10-22_10-39](https://user-images.githubusercontent.com/147067/96876368-0a3c6900-1481-11eb-9b12-f30bb3ce94ea.png)

**Comment by ctapmex** [comment] 2020-11-27 18:09
Duplicate of #80

**Comment by ctapmex** [comment] 2020-11-27 19:40
fixed

**Closed by ctapmex** 2020-11-27 19:40 UTC
Labels: bug
